### ISSUE TITLE
NACK causes error 

### ISSUE THREAD

**Issue by pjathse** [Efferent-Health/HL7-dotnetcore#98]
Hi,
I'm new at HL7 so my apologies if I have the wrong end of the stick here.. but I am trying to send back a NACK when I get a message that doesn't parse.. 

I try your code from the Readme for parsing and dealing with failed parsing as an exception by using the bit of code you show for sending a NACK.

But the getNACK fails .. presumably because the massage is malformed??
So if there is a better way to send back a message to the client telling them that their message doesn't parse I would appreciate it if you could let me know.
Thanks
PJ 

```csharp
Message message = new Message(strMsg);

// Parse this message

bool isParsed = false;

try
{
    isParsed = message.ParseMessage();
}
catch(Exception ex)
{
    // Handle the exception THIS CAUSES A STACK DUMP
Message nack = message.GetNACK("AR", "Message didn't parse");
}

```

And the stackdump looks like:
System.Collections.Generic.KeyNotFoundException: The given key 'MSH' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at HL7.Dotnetcore.Message.createAckMessage(String code, Boolean isNack, String errMsg, Boolean bypassValidation)
   at HL7.Dotnetcore.Message.GetNACK(String code, String errMsg, Boolean bypassValidation)
   at IHIIndexRestfulAPI.Controllers.HL7APIController.Patient(Nullable`1 mirthMessageID, Boolean includeDetail) in C:\Users\user\Source\Repos\IHI-Integration\IHIIndexRestfulAPI\Controllers\HL7APIController.cs:line 73
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context

**Comment by jaime-olivares** [comment]
hi @pjathse,
I will need the message for testing. You may want to anonymize it, but try to keep as most as possible.

**Comment by pjathse** [comment]
Hi,
Sorry, I should have provided a message.
This is what I’m testing with..

MSH|^~\\&|^1.2.372.980010.1.2^ISO|^1.2.372.980010.1.2^ISO|^1.2.372.980010.1.2^ISO|^1.2.372.980010.1.2^ISO|20200507115511|SEEDING|ADT^A01^ADT_A01|I

Best Regards
PJ

**Comment by pjathse** [comment]
If the message doesn't parse, then getNACK returns a null, or so it would appear.

**Comment by jaime-olivares** [comment]
I see your message is throwing an exception. In that situation, you cannot invoke GetNACK().

Not sure if you should send a NACK at all, as the header may contain corrupted information. It totally depends on your own implementation logic.

**Comment by pjathse** [comment]
Ok, thanks.
PJ
